We import the function:
        >>> BG = __import__("7-base_geometry").BaseGeometry

Check docstring:
         >>> m = __import__("7-base_geometry").__doc__
         >>> len(m) > 1
         True

Check class docstring:
         >>> c = __import__("7-base_geometry").BaseGeometry.__doc__
         >>> len(c) > 1
         True

Check method docstring:
	  >>> mod1 = __import__("7-base_geometry").BaseGeometry.area.__doc__
	  >>> len(mod1) > 1
	  True
	  >>> mod2 = __import__("7-base_geometry").BaseGeometry.integer_validator.__doc__
          >>> len(mod2) > 1
          True

Check area failure:
	  >>> b = BG()
	  >>> b.area()
	  Traceback (most recent call last):
	  ...
	  Exception: area() is not implemented

Check multiple area arguments:
	  >>> b.area(1)
	  Traceback (most recent call last):
          ...
	  TypeError: area() takes 1 positional argument but 2 were given

Check passing integer validation:
	  >>> b.integer_validator("integer", 1)

Check integer == 0:
	  >>> b.integer_validator("integer", 0)
	  Traceback (most recent call last):
          ...
          ValueError: integer must be greater than 0

Check integer < 0;
	  >>> b.integer_validator("integer", -8)
	  Traceback (most recent call last):
          ...
          ValueError: integer must be greater than 0

Check non-integer:
	  >>> b.integer_validator("bool", True)
	  Traceback (most recent call last):
           ...
          TypeError: complex must be an integer
	  >>> b.integer_validator("string", "yupo")
          Traceback (most recent call last):
         ...
          TypeError: bool must be an integer
	  >>> b.integer_validator("float", 1.5)
          Traceback (most recent call last):
          ...
          TypeError: string must be an integer
	  >>> b.integer_validator("tuple", (3, 8))
          Traceback (most recent call last):
          ...
          TypeError: float must be an integer
	  >>> b.integer_validator("complex", complex(4, 4))
          Traceback (most recent call last):
          ...
          TypeError: tuple must be an integer
	  >>> b.integer_validator("list", [5, 2, 9])
	  Traceback (most recent call last):
          ...
          TypeError: dict must be an integer
	  >>> b.integer_validator("set", {"love", "coding"})
          Traceback (most recent call last):
           ...
          TypeError: frozenset must be an integer
	  >>> b.integer_validator("bytes", b"bytes")
          Traceback (most recent call last):
         ...
          TypeError: list must be an integer
	  >>> b.integer_validator("dict", {"key": "value"})
          Traceback (most recent call last):
          ...
          TypeError: set must be an integer
	  >>> b.integer_validator("frozenset", frozenset(["you", "there"]))
          Traceback (most recent call last):
          ...
          TypeError: bytes must be an integer
	  >>> b.integer_validator("bytearrays", bytearray(b"bytes"))
          Traceback (most recent call last):
          ...
          TypeError: bytearrays must be an integer

Check lack of arguments to integer_validator:
	  >>> b.integer_validator()
	  Traceback (most recent call last):
          ...
	  TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

Check 1 argument given to integer_validator:
	  >>> b.integer_validator("integer")
	  Traceback (most recent call last):
          ...
	  TypeError: integer_validator() missing 1 required positional argument: 'value'

Check for multiple arguments:
	  >>> b.integer_validator("integer", 8, 6)
	  Traceback (most recent call last):
          ...
	  TypeError: integer_validator() takes 3 positional arguments but 4 were given
